### ISSUE TITLE
ended homework

### ISSUE THREAD

**Issue by vickyantre** [Artinov/home-work-13-vickyantre#1]

**Comment by eko24ive** [comment]
Hi @vickyantre I have an error running your code:
```
λ node index.js
module.js:471
    throw err;
    ^

Error: Cannot find module 'calculator'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\workspace\students\home-work-13-vickyantre\index.js:3:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

It seems that you don't have module `calculator` in package.json file (which is absent too). Fix it and ping me when you commit this changes.

Besides that I can already give you huge plus for using third-party package !

**Comment by vickyantre** [comment]
Hello, @eko24ive. I have added package.json file.

**Comment by eko24ive** [comment]
Awesome, now your app is capable to be installed !
I can tell that what I saw is probably the most laconic implementation of homework, which means you've able to achieve desireble result using small amout of code lines without damaging its readability, and this is perfect. Also app code is small because you've used third-party lib which is super great, becouse sometimes its better not to "invent" bycicle, while someone already did features you wanted to use.

Besides that, primary homework task was create server which capable of performing simple math with two numbers, and your app has overcome it because of using `calculator` package, which means I'm even able to get result for calculations like `http://localhost:3000/1*(2-1)`.

Again, this is outstanding work, keep it up !

**Comment by vickyantre** [comment]
Thank you, I will)
